### ISSUE TITLE
Elasticsearch curator

### ISSUE THREAD

**Issue by DStorck** [samsung-cnct/chart-elasticsearch#2]
_From @leahnp on August 1, 2017 22:40_

In conjunction with: https://github.com/samsung-cnct/k2-charts/issues/63
Delete logs after 2 weeks

_Copied from original issue: samsung-cnct/elasticsearch-kubernetes#8_

**Comment by DStorck** [comment]
_From @leahnp on August 2, 2017 21:31_

This is probably related to: https://github.com/samsung-cnct/elasticsearch-kubernetes/issues/3

**Comment by DStorck** [comment]
currently dealing with this: https://github.com/kubernetes/kubernetes/issues/51939
(inability to create cronjob)  . error is : 
```
error: error validating "es-curator.yaml": error validating data: the server could not find the requested resource
```
seems like it is an issue of  batch/v2alpha1 API being turned on by passing` --runtime-config=batch/v2alpha1=true` while bringing up the API server

**Comment by DStorck** [comment]
Curator is currently working on my fluent-bit -> elasticsearch pipeline, just working out the kinks of which filters and actions to use to delete indices older than two weeks.

**Comment by DStorck** [comment]
next bug - curator is using two filters to delete out indices with documents older than two weeks (for testing purposes, 1 day). it looks like this: 
```
        action: delete_indices
        description: >-
          Delete indices older than 1 day (based on index name), for logstash-
          prefixed indices.
        options:
          timeout_override:
          continue_if_exception: False
          disable_action: False
          ignore_empty_list: True
        filters:
        - filtertype: pattern
          kind: prefix
          value: logstash-
          exclude: False
        - filtertype: age
          source: field_stats
          direction: older
          unit: days
          unit_count: 1
          field: '@timestamp'
          stats_result: min_value
```
I ran this yesterday and it deleted all documents and the index for the day before ( 9/19, the first day of the cluster). However, this morning when I looked at es again,  curator had failed to take down yesterday's indices and documents because somehow an index had been created for two days ago ( day 1 of the cluster). With no  actual documents to check timestamp against, I was greeted with this error : 
```
Failed to complete action: delete_indices. <class 'curator.exceptions.ActionError'>: Field "@timestamp" not found in index "logstash-2017.09.19" 
```
A look at the current indices showed: 
```
health status index               uuid                   pri rep docs.count docs.deleted store.size pri.store.size
green  open   logstash-2017.09.20 vQ06hfLuSRmrctDt-Ejkyg   5   1    2264044            0      3.4gb          1.7gb
green  open   logstash-2017.09.21 lHspQ9QoR7eAaX4H_IhTdg   5   1    3535778            0      7.2gb          3.2gb
green  open   logstash-2017.09.19 kuRXxBRLSJywe1Qi9DsguA   5   1          0            0      1.2kb           650b
```

Curator definitely had deleted the index, so I am now trying to investigate why this index was recreated. I manually deleted the index for 9/19, and once that was done, curator went ahead and deleted the index and all documents for 9/20 as expected.  Several hours later, no index for 9/20 has been recreated. I will keep the cluster alive until tomorrow to see if it shows up again, and if today's logs delete as they should.
